name = "FunWithMIPS"
uuid = "0e479ac7-59bd-45c4-a4a7-d8c46cda6d1e"
authors = ["Michael Wang"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
